"""
AttackVLM implementation.

This module is identified as the most complex due to its multiple inheritance
structure, differentiable optimization loops, and integration of computer
vision techniques (EOT, OCR masking).

Unit Tests (see testing/test_attackvlm.py):
------------------------------------------
1. test_untargeted_attack_positive: Basic functional test for the base optimization loop.
2. test_image_attack_positive: Verifies Image-to-Image attack logic and target embedding.
3. test_text_attack_positive: Verifies Text-to-Image attack logic using CLIP text embeddings.
4. test_attack_strength_zero: Edge case for zero perturbation limit.
5. test_attack_strength_negative: Failure mode for invalid input (negative strength).
6. test_attack_steps_zero: Edge case for optimization with zero iterations.
7. test_ocr_attack_positive: Verifies complex spatial masking logic in AttackVLMOCR.
8. test_attack_with_eot: Tests Expectation over Transformation (EOT) augmentations (noise, brightness, shift).
9. test_attack_invalid_image: Failure mode for malformed image inputs.
10. test_attack_large_strength: Edge case for extreme perturbation limits and clamping.
11. test_ocr_mask_large_kernel: Edge case for OCR masking with an unusually large dilation kernel.
12. test_ocr_mask_zero_area: Edge case for OCR masking with zero allowed area (maximum restriction).

These tests were chosen to cover the breadth of attack variants (Untargeted, Image, Text, OCR),
the robustness of the optimization loop under unusual hyperparameters (0 steps, 0 strength, large strength),
and the correctness of auxiliary features like EOT and masking.
"""
from abc import ABC, abstractmethod
import logging
import tempfile
from typing import Dict, List, Optional, Tuple
from collections.abc import Sequence
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from tqdm import tqdm

from ..interfaces import (
    TextTargetModel,
    TextAttackMethod,
    ImageTargetModel,
    ImageAttackMethod,
    UntargetedAttackMethod,
)

from ..models.clip_target import TextCLIPModel, PatchTextCLIPModel, ImageCLIPModel

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# ====================================================================================================
# AttackVLM base class

class _AttackVLM(ABC):
    """
    This base class for AttackVLM implements the core attack, but leaves some
    important helper methods abstract. The child classes below implement these
    methods in different ways by defining those helpers differently.

    + Every child class must implement a setup method which takes in any extra
      parameters for its attack, pre-computes embeddings if needed, and stores
      results in the class. The purpose of this method is to allow for pre-
      computation of values used in the loss function later.
    + Every child class must implement a step loss function, which the attack
      will try to minimize. This function must be differentiable.
    """
    def __init__(self, model: ImageTargetModel, device: Optional[str] = None):
        self.model = model
        self.device = device or "cuda"

    @abstractmethod
    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        """
        Compute the loss given the embedding for the current adversarial image,
        as generated by the model. Implementing subclasses that need to compare against
        target, clean, etc should store those as instance attributes.
        """
        pass # pragma: no cover

    @abstractmethod
    def setup(self, clean_t: torch.Tensor, *args, **kwargs) -> None:
        """
        Take in extra arguments and initialize targets or whatever is needed
        for this variant of the attack.
        All unknown arguments passed to `attack` will be passed to this method.
        """
        pass # pragma: no cover

    def mask(self, data):
        """
        Applied to delta after clamping. Does nothing here, but can be overridden.
        """
        return data

    def _run_attack(
        self,
        clean: Image.Image | Sequence[Image.Image],
		eps=16 / 255,
		alpha=2 / 255,
		steps=300,
		eot_samples: int = 1,
		eot_noise_std: float = 0.0,
		eot_brightness: float = 0.0,
		eot_shift_px: int = 0,
        *args, **kwargs
    ) -> Sequence[Image.Image]:
        if clean is None:
            raise TypeError("clean image(s) must not be None")
        single_image = isinstance(clean, Image.Image)
        if single_image:
            clean = [clean]
        if any(c is None for c in clean):
            raise TypeError("clean image(s) must not be None")
        batch_size = len(clean)
        clean_t = torch.stack([self._load_image_tensor(im) for im in clean])
        clean_embed = self.model.embed_image(clean_t)

        self.setup(clean_t, *args, **kwargs)

        delta = torch.empty_like(clean_t).uniform_(-eps, eps)
        delta = (clean_t + delta).clamp(0, 1) - clean_t
        delta.requires_grad_(True)

        best_loss = torch.full((batch_size,), float("inf"), device=self.device)
        best_adv = clean_t.clone()

        for i in tqdm(range(steps), desc="AttackVLM"):
            adv = (clean_t + delta).clamp(0, 1)
            loss = torch.zeros((batch_size,), device=self.device)
            n = max(1, int(eot_samples))

            for _ in range(n):
                adv_aug = self._eot_augment(adv, noise_std=eot_noise_std, brightness=eot_brightness, shift_px=eot_shift_px)
                adv_embed = self.model.embed_image(adv_aug)
                loss += self.compute_step_loss(adv_embed, clean_embed)

            loss = loss / n

            mask = (loss < best_loss)
            best_loss = torch.where(mask, loss, best_loss)
            best_adv = torch.where(mask.view(-1, 1, 1, 1), adv.detach().clone(), best_adv)

            loss = loss.mean()
            loss.backward()

            with torch.no_grad():
                if delta.grad is not None:
                    delta.data = delta.data - alpha * delta.grad.sign()
                    delta.data = delta.data.clamp(-eps, eps)
                    delta.data = self.mask(delta.data)
                    delta.data = (clean_t + delta.data).clamp(0, 1) - clean_t
                    delta.grad.zero_()

        output_images = []
        for image in best_adv:
            adv_np = image.cpu().permute(1, 2, 0).numpy()
            adv_np = (adv_np * 255).round().clip(0, 255).astype(np.uint8)
            output_images.append(Image.fromarray(adv_np))
        if single_image:
            output_images = output_images[0]
        return output_images

    @staticmethod
    def _strength_to_eps(strength: float, hyperparameters: Optional[Dict] = None) -> float:
        if strength < 0:
            raise ValueError("strength must be non-negative")
        hp = hyperparameters or {}
        max_eps = float(hp.get("max_eps", 32 / 255))
        if strength > 1.0:
            return min(strength / 255.0, max_eps)
        return min(strength * max_eps, max_eps)

    @staticmethod
    def _eot_augment(
        x: torch.Tensor,
		noise_std: float = 0.0,
		brightness: float = 0.0,
		shift_px: int = 0
    ) -> torch.Tensor:
        y = x
        if noise_std > 0:
            y = y + noise_std * torch.randn_like(y)
        if brightness > 0:
            scale = 1.0 + (2.0 * torch.rand((x.shape[0], 1, 1, 1), device=x.device) - 1.0) * brightness
            y = y * scale
        if shift_px > 0:
            dy = int(torch.randint(-shift_px, shift_px + 1, (1,), device=x.device).item())
            dx = int(torch.randint(-shift_px, shift_px + 1, (1,), device=x.device).item())
            y = torch.roll(y, shifts=(dy, dx), dims=(2, 3))
        return y.clamp(0, 1)

    def _load_image_tensor(self, image: Image.Image) -> torch.Tensor:
        """
        Load an image as a Tensor after converting to 512x512 float [0-1] format
        """
        image = image.convert("RGB").resize((512, 512))
        clean_np = np.array(image).astype(np.float32) / 255.0
        return torch.from_numpy(clean_np).permute(2, 0, 1).to(self.device)


# ====================================================================================================
# Subclasses of AttackVLM

class AttackVLMUntargeted(_AttackVLM, UntargetedAttackMethod):
    """
    AttackVLMUntargeted guides the adversarial image away from the clean image
    in an arbitary "direction", only seeking to minimize the semantic similarity
    between the clean and adversarial images.
    """
    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        return self.model(adv_embed, clean_embed)

    def setup(self, clean_t: torch.Tensor, *args, **kwargs) -> None:
        return None

    def attack(
        self,
        clean: Image.Image | Sequence[Image.Image],
        strength: float,
        hyperparameters: Optional[Dict] = None
    ) -> Image.Image | Sequence[Image.Image]:
        if not isinstance(clean, Image.Image) and len(clean) == 0:
            return []
        hp = hyperparameters or {}
        return self._run_attack(
            clean=clean,
            eps=self._strength_to_eps(strength, hp),
            alpha=float(hp.get("alpha", 2 / 255)),
            steps=int(hp.get("steps", 300)),
            eot_samples=int(hp.get("eot_samples", 1)),
            eot_noise_std=float(hp.get("eot_noise_std", 0.0)),
            eot_brightness=float(hp.get("eot_brightness", 0.0)),
            eot_shift_px=int(hp.get("eot_shift_px", 0)),
        )


class AttackVLMImage(_AttackVLM, ImageAttackMethod):
    """
    AttackVLMImage guides the adversarial image towards a target image.
    It can also optionally guide the image away from the original clean image in
    embedding space.
    """
    def __init__(self, model: ImageTargetModel, device: Optional[str] = None):
        super().__init__(model, device)

    def setup(
        self,
        clean_t: torch.Tensor | Sequence[Image.Image],
        target: Image.Image | Sequence[Image.Image],
		repel_clean: float = 0.35,
        *args, **kwargs
    ) -> None:
        target = [target] if isinstance(target, Image.Image) else target
        self.target_embed = torch.stack([self.get_target_features(t) for t in target])
        self.repel_clean = repel_clean

    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        sim_target = self.model(adv_embed, self.target_embed)
        sim_clean = self.model(adv_embed, clean_embed)
        step_loss = (-sim_target + self.repel_clean * sim_clean)
        return step_loss

    def get_target_features(self, target: Image.Image):
        target_pil = target.convert("RGB")
        target_np = np.array(target_pil.resize((512, 512))).astype(np.float32) / 255.0
        target_t = torch.from_numpy(target_np).permute(2, 0, 1).unsqueeze(0).to(self.device)
        with torch.no_grad():
            return self.model.embed_image(target_t, detach=True)

    def attack(
        self,
        clean: Image.Image,
        target: Image.Image,
        strength: float,
        hyperparameters: Optional[Dict] = None
    ) -> Image.Image | Sequence[Image.Image]:
        if not isinstance(clean, Image.Image) and len(clean) == 0:
            return []
        hp = hyperparameters or {}
        return self._run_attack(
            clean=clean,
            target=target,
            eps=self._strength_to_eps(strength, hp),
            alpha=float(hp.get("alpha", 2 / 255)),
            steps=int(hp.get("steps", 300)),
            eot_samples=int(hp.get("eot_samples", 1)),
            eot_noise_std=float(hp.get("eot_noise_std", 0.0)),
            eot_brightness=float(hp.get("eot_brightness", 0.0)),
            eot_shift_px=int(hp.get("eot_shift_px", 0)),
            repel_clean=float(hp.get("repel_clean", 0.35)),
        )


class AttackVLMText(_AttackVLM, TextAttackMethod):
    """
    AttackVLMText guides the adversarial image towards a text description.
    It can optionally guide the image away from the original clean image in
    embedding space, and also away from an original text description, which
    could be a known caption or a prompt used to generate the clean image.
    """
    def __init__(self, model: TextTargetModel, device: Optional[str] = None):
        super().__init__(model, device)

    def setup(
        self,
        clean_t: torch.Tensor | Sequence[Image.Image],
        target_text: str | Sequence[str],
        source_text: Optional[str] = None,
		repel_clean: float = 0.35,
		repel_source_text: float = 0.5,
        *args, **kwargs
    ) -> None:
        self.target_text_embed = self.model.embed_text(target_text)
        self.repel_clean = repel_clean
        self.repel_source_text = repel_source_text
        if source_text:
            self.source_text_embed = self.model.embed_text(source_text)
        else:
            self.source_text_embed = None

    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        sim_text = self.model(adv_embed, self.target_text_embed)
        sim_clean = self.model(adv_embed, clean_embed)
        step_loss = -sim_text + self.repel_clean * sim_clean
        if self.source_text_embed is not None:
            sim_source_text = self.model(adv_embed, self.source_text_embed)
            step_loss = step_loss + self.repel_source_text * sim_source_text
        return step_loss

    def attack(
        self,
        clean: Image.Image,
        target: str,
        strength: float,
        hyperparameters: Optional[Dict] = None
    ) -> Image.Image | Sequence[Image.Image]:
        if not isinstance(clean, Image.Image) and len(clean) == 0:
            return []
        hp = hyperparameters or {}
        return self._run_attack(
            clean=clean,
            target_text=target,
            source_text=hp.get("source_text"),
            eps=self._strength_to_eps(strength, hp),
            alpha=float(hp.get("alpha", 2 / 255)),
            steps=int(hp.get("steps", 300)),
            eot_samples=int(hp.get("eot_samples", 1)),
            eot_noise_std=float(hp.get("eot_noise_std", 0.0)),
            eot_brightness=float(hp.get("eot_brightness", 0.0)),
            eot_shift_px=int(hp.get("eot_shift_px", 0)),
            repel_clean=float(hp.get("repel_clean", 0.35)),
            repel_source_text=float(hp.get("repel_source_text", 0.5)),
        )


class AttackVLMOCR(AttackVLMText, TextAttackMethod):
    """
    AttackVLMOCR is an extension of AttackVLMText which limits perturbations around areas detected as text.
    """
    def setup(
        self,
        clean_t: torch.Tensor,
		ocr_edge_quantile: float = 0.88,
		ocr_std_quantile: float = 0.70,
		ocr_dilate_kernel: int = 7,
		ocr_max_area_ratio: float = 0.22,
        *args, **kwargs
    ) -> None:
        super().setup(clean_t, *args, **kwargs)
        if clean_t.ndim == 3:
            clean_t = clean_t.unsqueeze(0)
        self.perturbation_mask = self._build_text_like_mask(
            clean_t, edge_quantile=ocr_edge_quantile, std_quantile=ocr_std_quantile,
            dilate_kernel=ocr_dilate_kernel, max_area_ratio=ocr_max_area_ratio
        )

    #override
    def mask(self, data):
        return data * self.perturbation_mask

    def attack(
        self,
        clean: Image.Image | Sequence[Image.Image],
        target: str,
        strength: float,
        hyperparameters: Optional[Dict] = None
    ) -> Image.Image | Sequence[Image.Image]:
        if not isinstance(clean, Image.Image) and len(clean) == 0:
            return []
        hp = hyperparameters or {}
        return self._run_attack(
            clean=clean,
            target_text=target,
            source_text=hp.get("source_text"),
            eps=self._strength_to_eps(strength, hp),
            alpha=float(hp.get("alpha", 2 / 255)),
            steps=int(hp.get("steps", 300)),
            eot_samples=int(hp.get("eot_samples", 1)),
            eot_noise_std=float(hp.get("eot_noise_std", 0.0)),
            eot_brightness=float(hp.get("eot_brightness", 0.0)),
            eot_shift_px=int(hp.get("eot_shift_px", 0)),
            repel_clean=float(hp.get("repel_clean", 0.35)),
            repel_source_text=float(hp.get("repel_source_text", 0.5)),
            ocr_edge_quantile=float(hp.get("ocr_edge_quantile", 0.88)),
            ocr_std_quantile=float(hp.get("ocr_std_quantile", 0.70)),
            ocr_dilate_kernel=int(hp.get("ocr_dilate_kernel", 7)),
            ocr_max_area_ratio=float(hp.get("ocr_max_area_ratio", 0.22)),
        )

    @staticmethod
    def _build_text_like_mask(
        clean_t: torch.Tensor,
        edge_quantile: float,
        std_quantile: float,
        dilate_kernel: int,
        max_area_ratio: float,
    ) -> torch.Tensor:
        gray = 0.299 * clean_t[:, 0:1, :, :] + 0.587 * clean_t[:, 1:2, :, :] + 0.114 * clean_t[:, 2:3, :, :]
        sobel_x = torch.tensor([[[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]], dtype=gray.dtype, device=gray.device).unsqueeze(1)
        sobel_y = torch.tensor([[[-1, -2, -1], [0, 0, 0], [1, 2, 1]]], dtype=gray.dtype, device=gray.device).unsqueeze(1)
        gx = F.conv2d(gray, sobel_x, padding=1)
        gy = F.conv2d(gray, sobel_y, padding=1)
        grad = torch.sqrt(gx * gx + gy * gy + 1e-12)

        gthr = torch.quantile(grad.flatten(1), edge_quantile, dim=1).view(-1, 1, 1, 1)
        edge_mask = (grad >= gthr).float()

        mean = F.avg_pool2d(gray, kernel_size=9, stride=1, padding=4)
        mean2 = F.avg_pool2d(gray * gray, kernel_size=9, stride=1, padding=4)
        std = torch.sqrt((mean2 - mean * mean).clamp(min=0.0) + 1e-12)
        sthr = torch.quantile(std.flatten(1), std_quantile, dim=1).view(-1, 1, 1, 1)
        std_mask = (std >= sthr).float()

        mask = edge_mask * std_mask
        k = int(max(3, dilate_kernel))
        if k % 2 == 0:
            k += 1
        for _ in range(2):
            mask = F.max_pool2d(mask, kernel_size=k, stride=1, padding=k // 2)

        if mask.mean().item() > max_area_ratio:
            cgrad = grad * mask
            cthr = torch.quantile(cgrad.flatten(1), 1.0 - max_area_ratio, dim=1).view(-1, 1, 1, 1)
            mask = (cgrad >= cthr).float()
            mask = F.max_pool2d(mask, kernel_size=3, stride=1, padding=1)

        return mask.clamp(0, 1)
