"""
AttackVLM implementation.

Contains four classes which inherit from a base _AttackVLM abstract base class:
+ AttackVLMUntargeted     tries to move an image away from its original meaning,
  ----implements--------  but not in any particular direction.
  UntargetedAttackMethod  Requires an ImageTargetModel which can compare the
                          adversarial image to the clean image.

+ AttackVLMImage          tries to move an image towards another image.
  --implements-----       Requires an ImageTargetModel which can compare the
  ImageAttackMethod       adversarial image to the clean image.

+ AttackVLMText           tries to move an image towards a caption.
  --implements----        Requires a TextTargetModel which can compare the
  TextAttackMethod        adversarial image to the text prompt in a shared
                          semantic space.

+ AttackVLMOCR            is an extension of AttackVLMText which limits
  -implements-----        noise around detected text objects.
  TextAttackMethod

This AttackVLM implementation has been tested with CLIP so far, but it is designed
to be modular so you can theoretically drop in any model which implements the ImageTargetModel
or TextTargetModel interface.

Terminology used here:
- clean image: the input image which we want to subtly modify.
- target: an image or a piece of text which we want to covertly hide the "idea" of in the clean image.
- adversarial image: the output image, or an intermediate step of it, which should look like the
    clean image to a human but like the target image/text to a vision model.
- attack: a specific method of combining a clean image and a target into an adversarial image.
- (target) model: a small model which understands images and possibly text, which acts as a judge
    during the process to determine how similar two images, or an image and a caption, are.
"""
from abc import ABC, abstractmethod
import logging
import tempfile
from typing import Dict, List, Optional, Tuple
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from tqdm import tqdm

from ..interfaces import (
    TextTargetModel,
    TextAttackMethod,
    ImageTargetModel,
    ImageAttackMethod,
    UntargetedAttackMethod,
)

from ..models.clip_target import TextCLIPModel, PatchTextCLIPModel, ImageCLIPModel

logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# ====================================================================================================
# AttackVLM base class

class _AttackVLM(ABC):
    """
    This base class for AttackVLM implements the core attack, but leaves some
    important helper methods abstract. The child classes below implement these
    methods in different ways by defining those helpers differently.

    + Every child class must implement a setup method which takes in any extra
      parameters for its attack, pre-computes embeddings if needed, and stores
      results in the class. The purpose of this method is to allow for pre-
      computation of values used in the loss function later.
    + Every child class must implement a step loss function, which the attack
      will try to minimize. This function must be differentiable.
    """
    def __init__(self, model: ImageTargetModel, device: Optional[str] = None):
        self.model = model
        self.device = device or "cuda"

    @abstractmethod
    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        """
        Compute the loss given the embedding for the current adversarial image,
        as generated by the model. Implementing subclasses that need to compare against
        target, clean, etc should store those as instance attributes.
        """
        pass

    @abstractmethod
    def setup(self, clean_t: torch.Tensor, *args, **kwargs) -> None:
        """
        Take in extra arguments and initialize targets or whatever is needed
        for this variant of the attack.
        All unknown arguments passed to `attack` will be passed to this method.
        """
        pass

    def mask(self, data):
        """
        Applied to delta after clamping. Does nothing here, but can be overridden.
        """
        return data

    def attack(
        self,
        clean: Image.Image,
		eps=16 / 255,
		alpha=2 / 255,
		steps=300,
		eot_samples: int = 1,
		eot_noise_std: float = 0.0,
		eot_brightness: float = 0.0,
		eot_shift_px: int = 0,
        *args, **kwargs
    ) -> Image.Image:
        clean_t = self._load_image_tensor(clean)
        clean_embed = self.model.embed_image(clean_t)

        self.setup(clean_t, *args, **kwargs)

        delta = torch.empty_like(clean_t).uniform_(-eps, eps)
        delta = (clean_t + delta).clamp(0, 1) - clean_t
        delta.requires_grad_(True)

        best_loss = float("inf")
        best_adv = clean_t.clone()

        for i in tqdm(range(steps), desc="AttackVLM"):
            adv = (clean_t + delta).clamp(0, 1)
            loss = 0.0
            n = max(1, int(eot_samples))

            for _ in range(n):
                adv_aug = self._eot_augment(adv, noise_std=eot_noise_std, brightness=eot_brightness, shift_px=eot_shift_px)
                adv_embed = self.model.embed_image(adv_aug)
                loss += self.compute_step_loss(adv_embed, clean_embed)

            loss = loss / n

            if loss.item() < best_loss:
                best_loss = loss.item()
                best_adv = adv.detach().clone()

            loss.backward()

            with torch.no_grad():
                delta.data = delta.data - alpha * delta.grad.sign()
                delta.data = delta.data.clamp(-eps, eps)
                delta.data = self.mask(delta.data)
                delta.data = (clean_t + delta.data).clamp(0, 1) - clean_t

            delta.grad.zero_()

        adv_np = best_adv[0].cpu().permute(1, 2, 0).numpy()
        adv_np = (adv_np * 255).round().clip(0, 255).astype(np.uint8)
        return Image.fromarray(adv_np)

    @staticmethod
    def _eot_augment(
        x: torch.Tensor,
		noise_std: float = 0.0,
		brightness: float = 0.0,
		shift_px: int = 0
    ) -> torch.Tensor:
        y = x
        if noise_std > 0:
            y = y + noise_std * torch.randn_like(y)
        if brightness > 0:
            scale = 1.0 + (2.0 * torch.rand((x.shape[0], 1, 1, 1), device=x.device) - 1.0) * brightness
            y = y * scale
        if shift_px > 0:
            dy = int(torch.randint(-shift_px, shift_px + 1, (1,), device=x.device).item())
            dx = int(torch.randint(-shift_px, shift_px + 1, (1,), device=x.device).item())
            y = torch.roll(y, shifts=(dy, dx), dims=(2, 3))
        return y.clamp(0, 1)

    def _load_image_tensor(self, image: Image.Image) -> torch.Tensor:
        """
        Load an image as a Tensor after converting to 512x512 float [0-1] format
        """
        image = image.convert("RGB").resize((512, 512))
        clean_np = np.array(image).astype(np.float32) / 255.0
        return torch.from_numpy(clean_np).permute(2, 0, 1).unsqueeze(0).to(self.device)


# ====================================================================================================
# Subclasses of AttackVLM

class AttackVLMUntargeted(_AttackVLM, UntargetedAttackMethod):
    """
    AttackVLMUntargeted guides the adversarial image away from the clean image
    in an arbitary "direction", only seeking to minimize the semantic similarity
    between the clean and adversarial images.
    """
    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        return self.model(adv_embed, clean_embed)


class AttackVLMImage(_AttackVLM, ImageAttackMethod):
    """
    AttackVLMImage guides the adversarial image towards a target image.
    It can also optionally guide the image away from the original clean image in
    embedding space.
    """
    def __init__(self, model: ImageTargetModel, device: Optional[str] = None):
        super().__init__(model, device)

    def setup(
        self,
        clean_t: torch.Tensor,
        target_image_path: str,
		repel_clean: float = 0.35,
        *args, **kwargs
    ) -> None:
        self.target_embed = self.get_target_features(target_image_path)
        self.repel_clean = repel_clean

    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        sim_target = self.model(adv_embed, self.target_embed)
        sim_clean = self.model(adv_embed, clean_embed)
        step_loss = (-sim_target + self.repel_clean * sim_clean)

    def get_target_features(self, image_path):
        target_pil = Image.open(image_path).convert("RGB")
        target_np = np.array(target_pil.resize((512, 512))).astype(np.float32) / 255.0
        target_t = torch.from_numpy(target_np).permute(2, 0, 1).unsqueeze(0).to(self.device)
        with torch.no_grad():
            return self.model.embed_image(target_t, detach=True)


class AttackVLMText(_AttackVLM, TextAttackMethod):
    """
    AttackVLMText guides the adversarial image towards a text description.
    It can optionally guide the image away from the original clean image in
    embedding space, and also away from an original text description, which
    could be a known caption or a prompt used to generate the clean image.
    """
    def __init__(self, model: TextTargetModel, device: Optional[str] = None):
        super().__init__(model, device)

    def setup(
        self,
        clean_t: torch.Tensor,
        target_text: str,
        source_text: Optional[str] = None,
		repel_clean: float = 0.35,
		repel_source_text: float = 0.5,
        *args, **kwargs
    ) -> None:
        self.target_text_embed = self.model.embed_text(target_text)
        self.repel_clean = repel_clean
        self.repel_source_text = repel_source_text
        if source_text:
            self.source_text_embed = self.model.embed_text(source_text)
        else:
            self.source_text_embed = None

    def compute_step_loss(self, adv_embed, clean_embed) -> torch.Tensor:
        sim_text = self.model(adv_embed, self.target_text_embed)
        sim_clean = self.model(adv_embed, clean_embed)
        step_loss = -sim_text + self.repel_clean * sim_clean
        if self.source_text_embed:
            sim_source_text = self.model(adv_embed, self.source_text_embed)
            step_loss = step_loss + self.repel_source_text * sim_source_text
        return step_loss


class AttackVLMOCR(AttackVLMText, TextAttackMethod):
    """
    AttackVLMOCR is an extension of AttackVLMText which limits perturbations around areas detected as text.
    """
    def setup(
        self,
        clean_t: torch.Tensor,
		ocr_edge_quantile: float = 0.88,
		ocr_std_quantile: float = 0.70,
		ocr_dilate_kernel: int = 7,
		ocr_max_area_ratio: float = 0.22,
        *args, **kwargs
    ) -> None:
        super().setup(*args, **kwargs)
        self.perturbation_mask = self._build_text_like_mask(
            clean_t, edge_quantile=ocr_edge_quantile, std_quantile=ocr_std_quantile, dilate_kernel=ocr_dilate_kernel, max_area_ratio=ocr_max_area_ratio
        )

    #override
    def mask(self, data):
        return data * self.perturbation_mask

    @staticmethod
    def _build_text_like_mask(
        clean_t: torch.Tensor,
        edge_quantile: float,
        std_quantile: float,
        dilate_kernel: int,
        max_area_ratio: float,
    ) -> torch.Tensor:
        gray = 0.299 * clean_t[:, 0:1, :, :] + 0.587 * clean_t[:, 1:2, :, :] + 0.114 * clean_t[:, 2:3, :, :]
        sobel_x = torch.tensor([[[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]], dtype=gray.dtype, device=gray.device).unsqueeze(1)
        sobel_y = torch.tensor([[[-1, -2, -1], [0, 0, 0], [1, 2, 1]]], dtype=gray.dtype, device=gray.device).unsqueeze(1)
        gx = F.conv2d(gray, sobel_x, padding=1)
        gy = F.conv2d(gray, sobel_y, padding=1)
        grad = torch.sqrt(gx * gx + gy * gy + 1e-12)

        gthr = torch.quantile(grad.flatten(1), edge_quantile, dim=1).view(-1, 1, 1, 1)
        edge_mask = (grad >= gthr).float()

        mean = F.avg_pool2d(gray, kernel_size=9, stride=1, padding=4)
        mean2 = F.avg_pool2d(gray * gray, kernel_size=9, stride=1, padding=4)
        std = torch.sqrt((mean2 - mean * mean).clamp(min=0.0) + 1e-12)
        sthr = torch.quantile(std.flatten(1), std_quantile, dim=1).view(-1, 1, 1, 1)
        std_mask = (std >= sthr).float()

        mask = edge_mask * std_mask
        k = int(max(3, dilate_kernel))
        if k % 2 == 0:
            k += 1
        for _ in range(2):
            mask = F.max_pool2d(mask, kernel_size=k, stride=1, padding=k // 2)

        if mask.mean().item() > max_area_ratio:
            cgrad = grad * mask
            cthr = torch.quantile(cgrad.flatten(1), 1.0 - max_area_ratio, dim=1).view(-1, 1, 1, 1)
            mask = (cgrad >= cthr).float()
            mask = F.max_pool2d(mask, kernel_size=3, stride=1, padding=1)

        return mask.clamp(0, 1)

